<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Spifel.Application\Spifel.Application.csproj" />
    <ProjectReference Include="..\Spifel.Domain\Spifel.Domain.csproj" />
    <ProjectReference Include="..\Spifel.Infra.Data\Spifel.Infra.Data.csproj" />
  </ItemGroup>

</Project>
